"""empty message

Revision ID: 1c9a4c4f23bf
Revises: 21a192140439
Create Date: 2021-09-23 17:40:01.741336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9a4c4f23bf'
down_revision = '21a192140439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isActive')
    # ### end Alembic commands ###
