"""empty message

Revision ID: d8f6874be209
Revises: ae1e395209b4
Create Date: 2021-09-22 20:09:43.301552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f6874be209'
down_revision = 'ae1e395209b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###
